// Decompiled with JetBrains decompiler
// Type: MdxLib.ModelFormats.CMdl
// Assembly: MdxLib, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 17865964-456C-47B2-99EA-FF370F2E8526
// Assembly location: C:\Users\Devin\Downloads\MdxConverter\MdxLib.dll

using MdxLib.ModelFormats.Mdl;
using System;
using System.IO;
using System.Text;

namespace MdxLib.ModelFormats
{
  public sealed class CMdl : IModelFormat
  {
    public void Load(string Name, Stream Stream, MdxLib.Model.CModel Model)
    {
      CLoader Loader = Stream.CanRead ? new CLoader(Name, Stream) : throw new NotSupportedException("Unable to load \"" + Name + "\", the stream does not support reading!");
      MdxLib.ModelFormats.Mdl.CModel.Instance.Load(Loader, Model);
      Loader.Attacher.Attach();
    }

    public void Save(string Name, Stream Stream, MdxLib.Model.CModel Model)
    {
      CSaver Saver = Stream.CanWrite ? new CSaver(Name, Stream) : throw new NotSupportedException("Unable to save \"" + Name + "\", the stream does not support writing!");
      Saver.WriteWord(this.BuildHeader(Name));
      MdxLib.ModelFormats.Mdl.CModel.Instance.Save(Saver, Model);
      Saver.WriteToStream();
    }

    private string BuildHeader(string Name)
    {
      StringBuilder stringBuilder = new StringBuilder();
      stringBuilder.AppendLine("//+-----------------------------------------------------------------------------");
      stringBuilder.AppendLine("//|");
      stringBuilder.AppendLine("//| " + Name.Replace("\n", "").Replace("\r", ""));
      stringBuilder.AppendLine("//| Generated by MdxLib v1.04 (written by Magnus Ostberg, aka Magos)");
      stringBuilder.AppendLine("//| " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
      stringBuilder.AppendLine("//| http://www.magosx.com");
      stringBuilder.AppendLine("//|");
      stringBuilder.AppendLine("//+-----------------------------------------------------------------------------");
      return stringBuilder.ToString();
    }
  }
}
